updated Copernicus-audio

diff --git a/bin/Copernicus-audio b/bin/Copernicus-audio
--- a/bin/Copernicus-audio
+++ b/bin/Copernicus-audio
@@ -6,7 +6,8 @@ if [[ `hostname` = "copernicus" ]]; then
   alias notify-send='notify-send -a'
   RESPONSE=$(playerctl metadata --format 'artist="{{xesam:artist}}"; title="{{xesam:title}}"; album="{{xesam:album}}"; track="{{xesam:trackNumber}}"; year="{{year}}"; playStatus="{{lc(status)}}"; position="{{duration(position)}}"; length="{{duration(mpris:length)}}"')
 else
-  RESPONSE=$(ssh -x copernicus ${(F)0:t} "${@}")
+  RESPONSE=$(ssh -x copernicus ${(F)0:t} "${@}" || echo "title='Network Error'; artist='No response from Copernicus'")
+  echo $?
 fi
 
 echo $RESPONSE
