.

diff --git a/bin/Copernicus-audio b/bin/Copernicus-audio
--- a/bin/Copernicus-audio
+++ b/bin/Copernicus-audio
@@ -1,6 +1,7 @@
 #!/bin/zsh
 
 playerHost=copernicus
+#player=strawberry
 thisFile=${(F)0:t}
 
 if [[ "$1" == "--setx" ]]; then
@@ -14,7 +15,7 @@ if [[ `hostname` = "${playerHost}" ]]; then
   if [[ "${@}" = "stop" ]]; then
     RESPONSE='message="Stopped"'
   else
-    RESPONSE=$(playerctl -p strawberry metadata --format 'artist="{{xesam:artist}}"; song="{{xesam:title}}"; album="{{xesam:album}}"; track="{{xesam:trackNumber}}"; year="{{year}}"; playStatus="{{lc(status)}}"; position="{{duration(position)}}"; length="{{duration(mpris:length)}}"' 2>/dev/null || echo message='Error: No track is selected')
+    RESPONSE=$(playerctl ${player:+-p} ${player} metadata --format 'artist="{{xesam:artist}}"; song="{{xesam:title}}"; album="{{xesam:album}}"; track="{{xesam:trackNumber}}"; year="{{year}}"; playStatus="{{lc(status)}}"; position="{{duration(position)}}"; length="{{duration(mpris:length)}}"' 2>/dev/null || echo message='Error: No track is selected')
   fi
 
 else
