Updated gwSetEnv to handle Apollo, fixed prompt issues

diff --git a/bin/gwSetEnv b/bin/gwSetEnv
--- a/bin/gwSetEnv
+++ b/bin/gwSetEnv
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+unset GW_PLATFORM
 case $PWD in
     */carbon/*)
         export GW_PLATFORM=carbon
@@ -13,118 +14,128 @@ case $PWD in
     */ferrite/*)
         export GW_PLATFORM=ferrite
         ;;
+    */apollo/*)
+        export GW_PLATFORM=apollo
+        ;;
     *)
-        echo "Could not determine platform version!" >&2
-        exit 1
+        echo "${0//$HOME/~}: Could not determine platform version!" >&2
+        unset GW_COLOR GW_PL GW_PLATFORM GW_PRODUCT GW_START_SCRIPT GW_TITLE
         ;;
 esac
 
-export GW_PRODUCT=`echo $PWD | sed "s_^.*/${GW_PLATFORM}/\([^/]*\).*_\1_"`
+if [ -n "$GW_PLATFORM" ]; then
+    export GW_PRODUCT=`echo $PWD | sed "s_^.*/${GW_PLATFORM}/\([^/]*\).*_\1_"`
 
-# # take the uppercase of the first char
-export GW_PL=`echo $GW_PLATFORM | sed 's/\(.\).*/\U\1/'`
-export GW_TITLE="$GW_PL:$GW_PRODUCT"
+    # # take the uppercase of the first char
+    export GW_PL=`echo $GW_PLATFORM | sed 's/\(.\).*/\U\1/'`
+    export GW_TITLE="$GW_PL:$GW_PRODUCT"
 
-case `uname` in
-    CYGWIN*)
-        _script_extension=.bat
-        ;;
-    *)
-        if [ "$GW_PLATFORM" = "ferrite" ]; then
-            _script_extension=
-        else
-            _script_extension=.sh
+    case `uname` in
+        CYGWIN*)
+            _script_extension=.bat
+            ;;
+        *)
+            if [ "$GW_PLATFORM" = "ferrite" ]; then
+                _script_extension=
+            else
+                _script_extension=.sh
+            fi
+            ;;
+    esac
+
+    setJavaHomeTo() {
+        local newHomeName=$1
+        eval local newHome=\$$newHomeName
+
+        if [ "$newHome" = "" ]; then
+            echo Error: $newHomeName is not set\!
+            exit 1
+        elif [ ! -d ${newHome} ]; then
+            echo Error: $newHomeName directory $newHome does not exist\!
+            exit 1
         fi
-        ;;
-esac
+        export JAVA_HOME=$newHome
+    }
 
-setJavaHomeTo() {
-    local newHomeName=$1
-    eval local newHome=\$$newHomeName
-
-    if [ "$newHome" = "" ]; then
-        echo Error: $newHomeName is not set\!
-        exit 1
-    elif [ ! -d ${newHome} ]; then
-        echo Error: $newHomeName directory $newHome does not exist\!
-        exit 1
-    fi
-    echo newHome must exist
-    export JAVA_HOME=$newHome
-}
-
-export GW_START_SCRIPT=./gwb
-case $GW_PLATFORM in
-    carbon)
-        export GW_START_SCRIPT=bin/$GW_PRODUCT${_script_extension}
-        export IDEA_HOME=$IDEA11_HOME
-        export JAVA_HOME=$JAVA6_HOME
-        setJavaHomeTo JAVA6_HOME
-        ;;
-    diamond)
-        export GW_START_SCRIPT=bin/$GW_PRODUCT${_script_extension}
-        export IDEA_HOME=$IDEA12_HOME
-        export JAVA_HOME=$JAVA6_HOME
-        setJavaHomeTo JAVA6_HOME
-       ;;
-    emerald)
-        export GW_START_SCRIPT=bin/$GW_PRODUCT${_script_extension}
-        export IDEA_HOME=$IDEA12_HOME
-        export JAVA_HOME=$JAVA7_HOME
-        setJavaHomeTo JAVA7_HOME
-        ;;
-    ferrite)
-        export IDEA_HOME=$IDEA15_HOME
-        export JAVA_HOME=$JAVA8_HOME
-        setJavaHomeTo JAVA8_HOME
-        ;;
-    *)
-        echo "Could not determine platform version!" >&2
-        exit 1
-        ;;
-esac
+    export GW_START_SCRIPT=./gwb
+    case $GW_PLATFORM in
+        carbon)
+            export GW_START_SCRIPT=bin/$GW_PRODUCT${_script_extension}
+            export IDEA_HOME=$IDEA11_HOME
+            export JAVA_HOME=$JAVA6_HOME
+            setJavaHomeTo JAVA6_HOME
+            ;;
+        diamond)
+            export GW_START_SCRIPT=bin/$GW_PRODUCT${_script_extension}
+            export IDEA_HOME=$IDEA12_HOME
+            export JAVA_HOME=$JAVA6_HOME
+            setJavaHomeTo JAVA6_HOME
+           ;;
+        emerald)
+            export GW_START_SCRIPT=bin/$GW_PRODUCT${_script_extension}
+            export IDEA_HOME=$IDEA12_HOME
+            export JAVA_HOME=$JAVA7_HOME
+            setJavaHomeTo JAVA7_HOME
+            ;;
+        ferrite)
+            export IDEA_HOME=$IDEA15_HOME
+            export JAVA_HOME=$JAVA8_HOME
+            setJavaHomeTo JAVA8_HOME
+            ;;
+       apollo)
+            export IDEA_HOME=$IDEA15_HOME
+            export JAVA_HOME=$JAVA8_HOME
+            setJavaHomeTo JAVA8_HOME
+            ;;
+        *)
+            export IDEA_HOME=$IDEA15_HOME
+            export JAVA_HOME=$JAVA8_HOME
+            setJavaHomeTo JAVA8_HOME
+            ;;
+    esac
 
 
-_lib_jars='./lib/*jar'
-CLASSPATH=$JAVA_HOME/lib/\*jar:${CLASSPATH%:$_lib_jars}:$_lib_jars
+    _lib_jars='./lib/*jar'
+    CLASSPATH=$JAVA_HOME/lib/\*jar:${CLASSPATH%:$_lib_jars}:$_lib_jars
 
-typeset -p AARDVARK_HOME ANT_HOME M2_HOME IDEA_HOME JAVA_HOME
-echo
+    typeset -p AARDVARK_HOME ANT_HOME M2_HOME IDEA_HOME JAVA_HOME
+    echo
 
-export PATH=${JAVA_HOME}/bin:${IDEA_HOME}/bin:${PATH}
+    export PATH=${JAVA_HOME}/bin:${IDEA_HOME}/bin:${PATH}
 
-java -version
+    java -version
 
-case $GW_PRODUCT in
-    ab)
-        # bright white text on aqua
-        $ifCygwin export GW_COLOR=3F
-        ;;
-    bc)
-        # bright white text on red
-        $ifCygwin export GW_COLOR=2F
-        ;;
-    cc)
-        # bright white text on blue
-        $ifCygwin export GW_COLOR=1F
-        ;;
-    pc)
-        # bright white text on red
-        e$ifCygwin xport GW_COLOR=4F
-        ;;
-    *)
-        $ifCygwin export GW_COLOR=0F
-        ;;
-esac
+    case $GW_PRODUCT in
+        ab)
+            # bright white text on aqua
+            $ifCygwin export GW_COLOR=3F
+            ;;
+        bc)
+            # bright white text on red
+            $ifCygwin export GW_COLOR=2F
+            ;;
+        cc)
+            # bright white text on blue
+            $ifCygwin export GW_COLOR=1F
+            ;;
+        pc)
+            # bright white text on red
+            e$ifCygwin xport GW_COLOR=4F
+            ;;
+        *)
+            $ifCygwin export GW_COLOR=0F
+            ;;
+    esac
 
-$ifCygwin typeset -p GW_COLOR
-typeset -p GW_PL GW_PLATFORM GW_PRODUCT GW_START_SCRIPT GW_TITLE
+    $ifCygwin typeset -p GW_COLOR
+    typeset -p GW_PL GW_PLATFORM GW_PRODUCT GW_START_SCRIPT GW_TITLE
 
-function echoList() {
-    for arg in $*; do
-        echo -e "\n$arg contains:"
-        eval echo \${${arg}} | tr ':' '\n' | cat -n
-    done
-}
+    function echoList() {
+        for arg in $*; do
+            echo -e "\n$arg contains:"
+            eval echo \${${arg}} | tr ':' '\n' | cat -n
+        done
+    }
 
-echoList PATH CLASSPATH
+    echoList PATH CLASSPATH
+fi
