known_hosts.constant - removed obsolete macos entry mkbanner - updated label for display ripgreprc - added separate switch for localized displaykeys setdisplayorder - new script to fix order of monitors at work

diff --git a/bin/mkbanner b/bin/mkbanner
--- a/bin/mkbanner
+++ b/bin/mkbanner
@@ -85,7 +85,7 @@ while [[ -n "$*" ]]; do
       switches+=(${1})
       ;;
     *)
-      txt=$1
+      txt=$*
       shift
       break
       ;;
@@ -97,10 +97,10 @@ if ((!$#txt)); then
   echo Error: missing text!
   usage
   exit 1
-elif ((${#*})); then
-  echo "Error: extra arguments after the text '${txt}': '${*}'!"
-  usage
-  exit 1
+#elif ((${#*})); then
+#  echo "Error: extra arguments after the text '${txt}': '${*}'!"
+#  usage
+#  exit 1
 fi
 
 LABEL=${GW_APPCODE}${GW_PLATFORM:0:1}
